services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
    networks:
      - red10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  php-fpm:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - red10
    environment:
      - DB_HOST=postgres
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
      - API_KEY=${API_KEY} 
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./config/nginx-web.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    networks:
      - red10
    depends_on:
      - php-fpm
      - postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

networks:
  red10:

volumes:
  db_data: