server {
    listen 80;
    server_name localhost;

    # raiz del src
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # configuración para procesar archivos PHP
    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Bloquea el acceso directo a la ruta real del panel de admin
# Cualquiera que intente entrar a /admin/perfil_admin.php recibirá un 403
#location /admin/perfil_admin.php {
#    deny all;
#}

# Ruta "pública" del panel, oculta la estructura de carpetas real
# /panel redirige internamente a /admin/perfil_admin.php sin que el usuario lo vea en la URL
#location /panel {
#    rewrite ^ /admin/perfil_admin.php last;
#}